### ISSUE TITLE
Error when run command: docker-compose up -d

### ISSUE THREAD

**Issue by quangdongst** [igorsuhinin/docker-nginx-php-apache-mysql-nodejs-phpmyadmin#1]
Hi You
I installed docker, docker-compose on mac osx 10.13.6, But I run command `docker-compose up -d` . I get error
`E: There are problems and -y was used without --force-yes
ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y nginx' returned a non-zero code: 100`

I try to changed config file docker-compose.yml at ports 81:81. But I can not resolve it. Please help me to check it, Thank you

**Comment by quangdongst** [comment]
I tried change file https://github.com/igorsuhinin/docker-nginx-php-apache-mysql-nodejs-phpmyadmin/blob/master/etc/nginx/Dockerfile. It work ok
`FROM debian:jessie

RUN sed -i 's;http://archive.debian.org/debian/;http://deb.debian.org/debian/;' /etc/apt/sources.list
RUN printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list

RUN apt-get update && apt-get install -y --force-yes nginx

RUN rm /etc/nginx/sites-available/default

RUN rm /etc/nginx/sites-enabled/default

RUN echo "upstream apache { server apache:8080 fail_timeout=0; }" > /etc/nginx/conf.d/upstream.conf

CMD ["nginx"]

EXPOSE 80`

**Comment by igorsuhinin** [comment]
Hello,

I didn't even expect that someone will be using my code :) 

Well, yeah, it looks like you found more or less working solution. However I think I'll update it soon.I think Apache can be removed from the list of the software as nginx + php-fpm should work just fine without Apache. Also, it makes sense to update php-fpm to the latest 7.4 version.

**Comment by l33tx0** [comment]
update the code still getting same error

**Comment by Mayanktaker** [comment]
Please update code. :)
